### ISSUE TITLE
Import to Crowdin and `locale/de/subsurface.cfg` file

### ISSUE THREAD

**Issue by dima74** [NathaU/factorio-subsurface#1]
Hi, thanks for the interest in [factorio-mods-localization](https://github.com/dima74/factorio-mods-localization)!

I noticed the initial import to Crowdin didn't work because of different names (`locale/en/en.cfg` vs `locale/de/subsurface.cfg`). After deletion of `locale/de/subsurface.cfg` in 33e6f39 import to Crowdin was successful, but now `de` file is missing. So if you want, please restore `locale/de/subsurface.cfg` in github repository, and I will import it to Crowdin (now it will work because names will be the same - `locale/de/subsurface.cfg` and `locale/en/subsurface.cfg`)

**Comment by NathaU** [comment]
Hi,
I deleted `locale/de/subsurface.cfg` because I wanted it to be translated on Crowdin and pushed by your bot. If I restore it, will new translation be written into it?
`locale/en/en.cfg` was just renamed to `locale/en/subsurface.cfg` to not have language names in the file name.

**Comment by dima74** [comment]
> If I restore it, will new translation be written into it?

Yes, any changes on Crowdin (such as translations for new strings or corrections of existing one) will be pushed by bot (weekly)

**Comment by NathaU** [comment]
So I did

**Comment by dima74** [comment]
Thanks!
