### ISSUE TITLE
Surface drill doesn't work creating an entrance

### ISSUE THREAD

**Issue by angrypidgeon123** [NathaU/factorio-subsurface#10]
Hacked a **solution** for myself: 
1. copied function clear_subsurface from 1.0.5 into 1.0.3 in control.lua
2. copied function place_resources from 1.0.5 into 1.0.3, and placed it before function clear_subsurface in the same file to prevent any referencing problems
3. added "if player.cursor_stack == nil then return end" line before "if player.cursor_stack.valid_for_read" because it was throwing a null error
4. don't know what other issues this may cause, but the drills work as before and I can launch into orbit unlike before. That means trying to dig into "level 2" will throw an error as before. Good thing I don't need a level 2
5. subterranean entrances can be removed with console /editor right click if needed
6. also the bold item needs be added in this line else crash "if is_subsurface(**game**.get_surface(event.surface_index)) then"

---------------------------

When it finishes "expected resources" it gets marked for deconstruction along with the chest I place at its exit to collect the stone. The deconstruction marker is set by another mod on all miners who finish resources but I don't think it has anything to do with this? Mod name is **AutoDeconstruct_0.3.12**

If I clear the deconstruction order still nothing happens, it's in "no mineable resources" mode and that's it

No entrance to the underground appears for a while after

https://ibb.co/2txgvfm

Same savegame / mods as in this post:
https://github.com/NathaU/factorio-subsurface/issues/8

EDIT: I removed **AutoDeconstruct_0.3.12**, still doesn't work, it got marked by PickerInventoryTools which does the same thing, will test without that next

EDIT2: Same story, surface driller didn't get marked but didn't produce an entrance either, neither on the surface or existing underground from 1.0.3

**Comment by NathaU** [comment]
That issue was fixed in ba5373
