### ISSUE TITLE
Concrete Tiles Placed upon hole creation not properly placed

### ISSUE THREAD

**Issue by Gam3GoB00M** [NathaU/factorio-subsurface#12]
Entrance Hitbox is still bugged unless you move 2 of the concrete tiles down 1, my suggestion? 
Rather than having it 2x2 have it be 3x2, so 2 extra tiles are placed below the hole

**Comment by NathaU** [comment]
What do you mean by "bugged"? What exactly does not work?

**Comment by Gam3GoB00M** [comment]
The concrete tiles placed with the new update work, but they arent properly placed
here's the issue 

https://github.com/NathaU/factorio-subsurface/assets/33811881/871b4080-8251-4b13-bb8d-ce343ddd92d4

**Comment by NathaU** [comment]
Okay, fixed in ded597
