### ISSUE TITLE
map gen interference 2

### ISSUE THREAD

**Issue by Gam3GoB00M** [NathaU/factorio-subsurface#13]
Terrain generation has been fixed, but subsurface has now decided to disable all uranium upon world load phase, no uranium on nauvis or the subsurface level, seems to be turning off uranium all together

![Factorio 1 1 104 2024-03-31 4_14_52 PM](https://github.com/NathaU/factorio-subsurface/assets/33811881/ab8a1fc2-a9f9-4591-b700-7f323d3923ae)
![Factorio 1 1 104 2024-03-31 4_13_27 PM](https://github.com/NathaU/factorio-subsurface/assets/33811881/c7c7d6e1-04c1-4f75-9a82-58c6b946374c)

**Comment by NathaU** [comment]
Just started a new world and it generated uranium in subsurface

**Comment by Gam3GoB00M** [comment]
Well that's the issue, it's disabling uranium generation on the main nauvis surface, and some of my other mods only work with uranium on the main surface to be functional

**Comment by NathaU** [comment]
> Well that's the issue, it's disabling uranium generation on the main nauvis surface, and some of my other mods only work with uranium on the main surface to be functional

Which mods? Do they prevent surface drilling?
That was my intention to move uranium into underground, to delay and make nuclear power more challenging.

**Comment by Gam3GoB00M** [comment]
It's a mod that adds water ore for some of my cargo ships made it so uranium needs to be mined off land, and every time I want subsurface running at the same time it just straight up deletes em from the water, maybe add an option to have uranium only generate on the subsurface or to have it generate in smaller quantities on both?

**Comment by NathaU** [comment]
yeah I'm gonna add settings for that
