### ISSUE TITLE
[idea / feature request] - fill in / close up tunnel entrances

### ISSUE THREAD

**Issue by Atlntssplayer** [NathaU/factorio-subsurface#15]
What do you think about the possibility of being able to fill up / close / make disappear a tunnel entrance with stone or land fill. You would need a lot of stone or landfill, probably more than the amount you got when you opened it.

Maybe I need the spot the entrance is on but when I excavated it I didn't plan ahead.
Maybe I moved away and don't want to leave a whole in the ground.
Maybe I opened another entrance at a better place and I don't want the old one to also be on the surface.
etc
I think it would be useful and rational if they could be filled in.

Please consider it.

Thanks! Awesome mod and has a lot of potential, keep up the good work!

**Comment by NathaU** [comment]
Yes, that's one of the things on my to-do list👍

Atlntssplayer ***@***.***> schrieb am Mo. 8. Apr. 2024 um
00:12:

**Comment by angrypidgeon123** [comment]
You can console /editor delete anything. Probably will disable achievements
