### ISSUE TITLE
AAI miners having unexpected interactions and crashing the game

### ISSUE THREAD

**Issue by green8751** [NathaU/factorio-subsurface#16]
[_autosave2.zip](https://github.com/NathaU/factorio-subsurface/files/14939135/_autosave2.zip)

as mentioned in my issue on factorio.com, they appear to learch, and then either take damage, get instantly destroyed, or get massively acerated, what i think is happening, after a little more thought, is they are being drawn onto the "rock" they are mining, and depending on how many objects its colliding with, and how the getting pushed out happens, they either take a massive amount of damage, or get over acerated deeper past the existing walls, and then got accelerated outside the existing part of the map by collisions before/as the new pocket formed.

autosave is last one i gave, and right before the first got destroyed by driving it forward, later ones were after clearing out land to the left mostly by hand, there is ore there, which may matter, although i think i destroyed a second one in the prosses. 3rd one got yeted after telling it to move diagonally across the ore and into the wall with a path planner (not a looping path, it was just a straight line)

**Comment by NathaU** [comment]
First thing, I got this error when I picked the Unit Remote Controller from inventory directly after laoding the save:
__Subsurface__/scripts/aai-miners.lua:34: attempt to index local 'miner_data' (a nil value)
Does this affect yours too?

**Comment by angrypidgeon123** [comment]
Yea I used a red AAI miner and just crashed. Updated the mod and now have other issues, testing..

**Comment by angrypidgeon123** [comment]
Applied the changes, now mining is 1.9Km/h, making player mining virtually unplayable even with Mk4 (4.5Km/h) :D and driving is 9.5Km/h-18Km/h

**Comment by green8751** [comment]
only mod i remember adding after worldgen is trail tree farm, i am not seeing any errors in my backup of the log from before the crash
