### ISSUE TITLE
Get Wires back crash

### ISSUE THREAD

**Issue by Atlntssplayer** [NathaU/factorio-subsurface#2]
Hey!

Sorry for resporting this here but I didn't find the repo for Get Wires back.

I got this error while I was building and somewhere off screen there was a biter wave and they might have destroyed a wall or turret, I'm not sure, I couldn't scroll there to check because the error message came up.

The mod Get Wires back (1.1.18) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event GetWiresBack::on_entity_died (ID 4)
__GetWiresBack__/control.lua:482: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__GetWiresBack__/control.lua:482: in function <__GetWiresBack__/control.lua:476>

Great mod by the way, keep up the good work!
THX.

**Comment by NathaU** [comment]
Why not posting it in the mod portal?
