### ISSUE TITLE
Game-breaking UPS drain when running a prospector scan on Nauvis

### ISSUE THREAD

**Issue by divine-ray** [NathaU/factorio-subsurface#29]
Having a prospector scanner fill it's progress bar causes it to render an ungodly amount of indicators (or whatever) on the six chunk radius it covers, slogging down the game to a creeping halt (I ran into 3 FPS/5 UPS), and even suspected a crash several times from lagging that much. 
running `/c render.clear("Subsurface")` fixed it (with help of _CodeGreen).
Please implement a fix for preventing the prospector to work on the standard surface layer.

**Comment by NathaU** [comment]
How does the corresponding subsurface look? Are there resources where the
prospector showed indicators?

Divine Ray ***@***.***> schrieb am Sa. 29. Juni 2024 um 18:01:

**Comment by divine-ray** [comment]
The respective subsurface was not dug (iirc) at that time, and from what i can tell the now-dug subsurface is chock-full of py's Bitumen Seeps (which i believe replace vanilla oil patches)

**Comment by divine-ray** [comment]
amendment: not just oil, apparently any of the big ore deposits. I accumulated 3.3bil aluminium reserve now...

**Comment by NathaU** [comment]
But this means that the prospector is working properly, there are issues in resource placement. They are mirrored so thats map gen setting related.
Could you provide a savegame?

**Comment by divine-ray** [comment]
[PyAE Subsurface.zip](https://github.com/user-attachments/files/16045203/PyAE.Subsurface.zip)
Said resource patches just pop up when expanding the cave, not from what i could tell be related to the prospector.
