### ISSUE TITLE
crashed when Space Exploration rocket launched the 1st time, froze from stone overflow

### ISSUE THREAD

**Issue by angrypidgeon123** [NathaU/factorio-subsurface#5]
1. crashed when Space Exploration rocket launched the 1st time

2. used a miner to dig a tunnel. As soon as the miner filled up instead of stopping, the stone fell on the ground and the cave kept filling up faster with stone drops than having space as it was being dug. When the stone filled up the cave, very fast actually, the game froze. In consequence setting an AI miner is not an option, one has to drive and monitor the miner's load

3. I set up a subsurface digger in the underground under the spot I wanted to exit at, testing whether it will dig up or down. Surprise, it dug into a parallel universe :D ; - I have to dig from surface to connect the tunnel, the idea being dodging biters attacking my logistics

The mod Subsurface - build beneath your base! (1.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Subsurface::on_tick (ID 0)
__Subsurface__/control.lua:122: attempt to index a nil value
stack traceback:
	__Subsurface__/control.lua:122: in function 'clear_subsurface'
	__Subsurface__/control.lua:150: in function <__Subsurface__/control.lua:134>

**Comment by NathaU** [comment]
All these errors dont exist

**Comment by NathaU** [comment]
Close

**Comment by NathaU** [comment]
why should I let someone tell me something like that when they're
complaining about bugs in an outdated version?


angrypidgeon123 ***@***.***> schrieb am Mo. 4. März 2024 um
17:08:

> Stop making public stuff, you're wasting people's time and insulting them
>

**Comment by angrypidgeon123** [comment]
To be fair your mod "subsurface" didn't crash this time around while
playing this mod list:

https://pastebin.com/mRCt4PnD

Cheers
