### ISSUE TITLE
subsurface 1.0.5 incompatible with resourcehighlighter-dark_2.5.2 and YARM_0.10.14

### ISSUE THREAD

**Issue by angrypidgeon123** [NathaU/factorio-subsurface#8]
They crash while loading subsurface 1.0.5
https://ibb.co/bgxvxf0
https://ibb.co/c6ngjz0

I know because of these sequence of events: I hopped in the rocket for 1st trip to orbit with subsurface 1.0.3 installed, it crashed. I updated to subsurface 1.0.5, resourcehighlighter-dark_2.5.2 and YARM_0.10.14 crashed, then loading without them I made it to orbit. They worked well with subsurface 1.0.3

121K downloaders
https://mods.factorio.com/mod/YARM

9.93K downloaders
https://mods.factorio.com/mod/resourcehighlighter-dark

Factorio 1.1.104

I'ld say it's a problem given the popularity of these mods

My other mods list: https://pastebin.com/41DMUY4b

Save game file if it helps: https://file.io/8s7DbmVvMNIc

**Comment by NathaU** [comment]
Fixed in aba2589
